#execution_env=local
execution_env=remote

appURL1=https://tutorialsninja.com/demo/
appURL2=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
Uname=test123897@mail.com
Pwd=Test@123
#Pwd=Test@1234
email=krish1@gmail.com